import os
import glob
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent

def compile_requirements():
    """
    Aggregates requirements.core.txt and all docnexus/plugins/*/requirements.txt
    into a single requirements.txt file.
    """
    print("Compiling requirements...")
    
    reqs = set()
    
    # 1. Read Core
    core_req = PROJECT_ROOT / "requirements.core.txt"
    if core_req.exists():
        print(f"  + core: {core_req}")
        with open(core_req, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    reqs.add(line)
    
    # 2. Read Plugins
    plugin_reqs = glob.glob(str(PROJECT_ROOT / "docnexus/plugins/*/requirements.txt"))
    for pr in plugin_reqs:
        print(f"  + plugin: {Path(pr).relative_to(PROJECT_ROOT)}")
        with open(pr, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    reqs.add(line)
    
    # 3. Write Output
    output = PROJECT_ROOT / "requirements.txt"
    with open(output, 'w') as f:
        f.write("# This file is auto-generated by scripts/compile_requirements.py\n")
        f.write("# Do not edit directly. Edit requirements.core.txt or plugin/requirements.txt\n\n")
        for req in sorted(reqs):
            f.write(f"{req}\n")
            
    print(f"Successfully compiled {len(reqs)} requirements to {output}")

if __name__ == "__main__":
    compile_requirements()
